---
# Exedra installer sequence (adapted from ALCI config for Calamares 3.4)
modules-search: [ local ]

instances:
  - module: shellprocess
    id: bootloader
    config: shellprocess-bootloader.conf
  - module: shellprocess
    id: exedra-cleanup
    config: shellprocess-exedra-cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - shellprocess@bootloader
      - shellprocess@exedra-cleanup
      - umount
  - show:
      - finished

branding: exedra
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
