#!/usr/bin/env python3
"""Generate .vnb recipes from a compact table.

Usage: gen-recipes.py <out-dir>
Writes <out-dir>/<category>/<name>.vnb for every row below.
Recipes intentionally carry NO sha256: install with
`venim install --no-check` (or VENIM_NO_CHECK=1).
"""
import os
import sys

# (cat, name, version, desc, license, homepage, kind, url, opts)
# kind: appimage | single | tarball
# opts: strip (tarball), bin (path under opt/<name> or dest bin name),
#       extras (["link:path", ...] under opt/<name>), inner (staged file
#       for zip singles), depends (default ["glibc"]), file (url basename
#       override), custom (raw install command list, overrides template)
RECIPES = [
    # --- browsers ---
    ("browsers", "zen-browser", "1.17", "Zen Browser", "MPL-2.0",
     "https://zen-browser.app", "tarball",
     "https://github.com/zen-browser/desktop/releases/latest/download/zen.linux-x86_64.tar.xz",
     {"strip": 1, "bin": "zen"}),
    ("browsers", "ungoogled-chromium", "144.0", "Ungoogled Chromium", "BSD-3",
     "https://ungoogled-software.github.io", "tarball",
     "https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/releases/download/144.0.7559.109-1/ungoogled-chromium_144.0.7559.109-1.linux.tar.xz",
     {"strip": 1, "bin": "chrome-linux/chrome"}),
    # --- editors ---
    ("editors", "vscode", "1.105", "Visual Studio Code", "MIT",
     "https://code.visualstudio.com", "tarball",
     "https://update.code.visualstudio.com/latest/linux-x64/stable",
     {"strip": 1, "bin": "code", "file": "vscode-linux-x64.tar.gz"}),
    ("editors", "zed", "0.209", "Zed editor", "GPL-3.0",
     "https://zed.dev", "tarball",
     "https://github.com/zed-industries/zed/releases/download/v0.209.1/zed-linux-x86_64.tar.gz",
     {"strip": 1, "bin": "zed.app/bin/zed"}),
    ("editors", "neovim", "0.11.5", "Neovim", "Apache-2.0",
     "https://neovim.io", "tarball",
     "https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-linux-x86_64.tar.gz",
     {"strip": 1, "bin": "bin/nvim"}),
    ("editors", "helix", "25.07.1", "Helix editor", "MPL-2.0",
     "https://helix-editor.com", "tarball",
     "https://github.com/helix-editor/helix/releases/download/25.07.1/helix-25.07.1-x86_64-linux.tar.xz",
     {"strip": 0, "bin": "hx"}),
    ("editors", "micro", "2.0.14", "micro editor", "MIT",
     "https://micro-editor.github.io", "tarball",
     "https://github.com/zyedidia/micro/releases/download/v2.0.14/micro-2.0.14-linux64-static.tar.gz",
     {"strip": 0, "bin": "micro"}),
    ("editors", "sublime-text", "4192", "Sublime Text", "proprietary",
     "https://www.sublimetext.com", "tarball",
     "https://download.sublimetext.com/sublime_text_build_4192_x64.tar.xz",
     {"strip": 0, "bin": "sublime_text/sublime_text"}),
    # --- terminals ---
    ("terminals", "kitty", "0.42.2", "Kitty terminal", "GPL-3.0",
     "https://sw.kovidgoyal.net/kitty", "tarball",
     "https://sw.kovidgoyal.net/kitty/binary/kitty-0.42.2.x86_64.txz",
     {"strip": 0, "bin": "bin/kitty"}),
    ("terminals", "hyper", "3.4.1", "Hyper terminal", "MIT",
     "https://hyper.is", "appimage",
     "https://github.com/vercel/hyper/releases/download/v3.4.1/Hyper-3.4.1-x86_64.AppImage",
     {}),
    # --- media ---
    ("media", "kdenlive", "25.12.0", "Kdenlive video editor", "GPL-3.0",
     "https://kdenlive.org", "appimage",
     "https://download.kde.org/stable/kdenlive/25.12/linux/kdenlive-25.12.0-x86_64.AppImage",
     {}),
    ("media", "shotcut", "25.12.15", "Shotcut video editor", "GPL-3.0",
     "https://shotcut.org", "tarball",
     "https://github.com/mltframework/shotcut/releases/download/v25.12.15/shotcut-linux-x86_64-251215.txz",
     {"strip": 0, "bin": "Shotcut.app/bin/shotcut"}),
    ("media", "olive", "0.2.0", "Olive video editor", "GPL-3.0",
     "https://olivevideoeditor.org", "appimage",
     "https://github.com/olivevideoeditor/olive/releases/download/0.2.0/Olive-0.2.0-x86_64.AppImage",
     {}),
    ("media", "audacity", "3.7.5", "Audacity audio editor", "GPL-2.0",
     "https://audacityteam.org", "appimage",
     "https://github.com/audacity/audacity/releases/download/Audacity-3.7.5/audacity-linux-3.7.5-x64.AppImage",
     {}),
    ("media", "lmms", "1.3.1", "LMMS music studio", "GPL-2.0",
     "https://lmms.io", "appimage",
     "https://github.com/LMMS/lmms/releases/download/v1.3.1/lmms-1.3.1-linux-x86_64.AppImage",
     {}),
    ("media", "musescore", "4.6.5", "MuseScore notation", "GPL-3.0",
     "https://musescore.org", "appimage",
     "https://github.com/musescore/MuseScore/releases/download/v4.6.5/MuseScore-Studio-4.6.5-x86_64.AppImage",
     {}),
    ("media", "ffmpeg", "8.0", "FFmpeg static build", "GPL-3.0",
     "https://ffmpeg.org", "tarball",
     "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz",
     {"strip": 1, "bin": "ffmpeg", "extras": ["ffprobe:ffprobe"]}),
    ("media", "yt-dlp", "latest", "yt-dlp video downloader", "Unlicense",
     "https://github.com/yt-dlp/yt-dlp", "single",
     "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp",
     {}),
    # --- office ---
    ("office", "libreoffice", "26.2.0", "LibreOffice", "MPL-2.0",
     "https://libreoffice.org", "appimage",
     "https://download.documentfoundation.org/libreoffice/stable/26.2.0/appimage/LibreOffice-fresh.standard-x86_64.AppImage",
     {}),
    ("office", "onlyoffice", "9.1.0", "ONLYOFFICE editors", "AGPL-3.0",
     "https://onlyoffice.com", "appimage",
     "https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v9.1.0/DesktopEditors_x86_64.AppImage",
     {}),
    ("office", "obsidian", "1.10.7", "Obsidian notes", "proprietary",
     "https://obsidian.md", "appimage",
     "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.7/Obsidian-1.10.7.AppImage",
     {}),
    ("office", "joplin", "3.4.12", "Joplin notes", "MIT",
     "https://joplinapp.org", "appimage",
     "https://github.com/laurent22/joplin/releases/download/v3.4.12/Joplin-3.4.12.AppImage",
     {}),
    ("office", "logseq", "0.10.9", "Logseq notes", "AGPL-3.0",
     "https://logseq.com", "appimage",
     "https://github.com/logseq/logseq/releases/download/0.10.9/Logseq-linux-x64-0.10.9.AppImage",
     {}),
    ("office", "zettlr", "3.4.6", "Zettlr markdown editor", "GPL-3.0",
     "https://zettlr.com", "appimage",
     "https://github.com/Zettlr/Zettlr/releases/download/v3.4.6/Zettlr-3.4.6-x86_64.AppImage",
     {}),
    ("office", "anytype", "0.48.6", "Anytype notes", "custom",
     "https://anytype.io", "appimage",
     "https://github.com/anyproto/anytype-ts/releases/download/v0.48.6/Anytype-0.48.6.AppImage",
     {}),
    ("office", "superproductivity", "11.0.11", "SuperProductivity tasks", "MIT",
     "https://super-productivity.com", "appimage",
     "https://github.com/johannesjo/super-productivity/releases/download/v11.0.11/superProductivity-11.0.11.AppImage",
     {}),
    ("office", "koodo-reader", "2.9.4", "Koodo Reader ebooks", "AGPL-3.0",
     "https://koodo.960960.xyz", "appimage",
     "https://github.com/troyeguo/koodo-reader/releases/download/v2.9.4/Koodo-Reader-2.9.4.AppImage",
     {}),
    ("office", "xournalpp", "1.3.6", "Xournal++ handwriting", "GPL-2.0",
     "https://xournalpp.github.io", "appimage",
     "https://github.com/xournalpp/xournalpp/releases/download/v1.3.6/xournalpp-1.3.6-x86_64.AppImage",
     {}),
    ("office", "drawio", "27.0.5", "draw.io diagrams", "Apache-2.0",
     "https://draw.io", "appimage",
     "https://github.com/jgraph/drawio-desktop/releases/download/v27.0.5/drawio-x86_64-27.0.5.AppImage",
     {}),
    ("office", "krita", "5.2.9", "Krita painting", "GPL-3.0",
     "https://krita.org", "appimage",
     "https://download.kde.org/stable/krita/5.2.9/krita-5.2.9-x86_64.appimage",
     {}),
    ("office", "darktable", "5.2.0", "darktable raw photos", "GPL-3.0",
     "https://darktable.org", "appimage",
     "https://github.com/darktable-org/darktable/releases/download/release-5.2.0/Darktable-5.2.0-x86_64.AppImage",
     {}),
    # --- chat ---
    ("chat", "telegram", "6.0", "Telegram", "GPL-3.0",
     "https://telegram.org", "tarball",
     "https://telegram.org/dl/desktop/linux",
     {"strip": 1, "bin": "Telegram", "file": "telegram.tar.xz"}),
    ("chat", "discord", "0.0.90", "Discord", "proprietary",
     "https://discord.com", "tarball",
     "https://discord.com/api/download?platform=linux&format=tar.gz",
     {"strip": 1, "bin": "Discord", "file": "discord.tar.gz"}),
    ("chat", "element", "1.12.9", "Element Matrix", "Apache-2.0",
     "https://element.io", "appimage",
     "https://github.com/element-hq/element-desktop/releases/download/v1.12.9/Element-1.12.9-x86_64.AppImage",
     {}),
    ("chat", "session", "1.18.7", "Session messenger", "GPL-3.0",
     "https://getsession.org", "appimage",
     "https://github.com/oxen-io/session-desktop/releases/download/v1.18.7/session-desktop-linux-x86_64-1.18.7.AppImage",
     {}),
    ("chat", "deltachat", "2.7.0", "Delta Chat", "GPL-3.0",
     "https://delta.chat", "appimage",
     "https://github.com/deltachat/deltachat-desktop/releases/download/v2.7.0/DeltaChat-2.7.0.AppImage",
     {}),
    ("chat", "mattermost", "5.12.2", "Mattermost", "Apache-2.0",
     "https://mattermost.com", "tarball",
     "https://releases.mattermost.com/desktop/5.12.2/mattermost-desktop-5.12.2-linux-x64.tar.gz",
     {"strip": 1, "bin": "mattermost-desktop"}),
    ("chat", "nheko", "0.12.0", "Nheko Matrix", "GPL-3.0",
     "https://nheko-reborn.github.io", "appimage",
     "https://github.com/Nheko-Reborn/nheko/releases/download/v0.12.0/nheko-0.12.0-x86_64.AppImage",
     {}),
]

DEV = [
    ("dev", "docker", "28.5.1", "Docker", "Apache-2.0",
     "https://docker.com", "tarball",
     "https://download.docker.com/linux/static/stable/x86_64/docker-28.5.1.tgz",
     {"strip": 1, "bin": "docker",
      "extras": ["dockerd:dockerd", "containerd:containerd", "ctr:ctr", "runc:runc"]}),
    ("dev", "kubectl", "1.34.2", "kubectl", "Apache-2.0",
     "https://kubernetes.io", "single",
     "https://dl.k8s.io/release/v1.34.2/bin/linux/amd64/kubectl", {}),
    ("dev", "k9s", "0.50.9", "k9s", "Apache-2.0",
     "https://k9scli.io", "tarball",
     "https://github.com/derailed/k9s/releases/download/v0.50.9/k9s_Linux_amd64.tar.gz",
     {"strip": 0, "bin": "k9s"}),
    ("dev", "lazygit", "0.55.1", "lazygit", "MIT",
     "https://github.com/jesseduffield/lazygit", "tarball",
     "https://github.com/jesseduffield/lazygit/releases/download/v0.55.1/lazygit_0.55.1_Linux_x86_64.tar.gz",
     {"strip": 0, "bin": "lazygit"}),
    ("dev", "lazydocker", "0.24.3", "lazydocker", "MIT",
     "https://github.com/jesseduffield/lazydocker", "tarball",
     "https://github.com/jesseduffield/lazydocker/releases/download/v0.24.3/lazydocker_0.24.3_Linux_x86_64.tar.gz",
     {"strip": 0, "bin": "lazydocker"}),
    ("dev", "gh", "2.79.0", "GitHub CLI", "MIT",
     "https://cli.github.com", "tarball",
     "https://github.com/cli/cli/releases/download/v2.79.0/gh_2.79.0_linux_amd64.tar.gz",
     {"strip": 1, "bin": "bin/gh"}),
    ("dev", "glab", "1.70.0", "GitLab CLI", "MIT",
     "https://gitlab.com/gitlab-org/cli", "tarball",
     "https://gitlab.com/gitlab-org/cli/-/releases/v1.70.0/downloads/glab_1.70.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "bin/glab"}),
    ("dev", "jj", "0.34.0", "Jujutsu VCS", "Apache-2.0",
     "https://jj-vcs.github.io", "tarball",
     "https://github.com/jj-vcs/jj/releases/download/v0.34.0/jj-v0.34.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "jj"}),
    ("dev", "gitui", "0.27.0", "gitui", "MIT",
     "https://github.com/gitui-org/gitui", "tarball",
     "https://github.com/gitui-org/gitui/releases/download/v0.27.0/gitui-linux-musl.tar.gz",
     {"strip": 0, "bin": "gitui"}),
    ("dev", "git-lfs", "3.7.1", "Git LFS", "MIT",
     "https://git-lfs.com", "tarball",
     "https://github.com/git-lfs/git-lfs/releases/download/v3.7.1/git-lfs-linux-amd64-v3.7.1.tar.gz",
     {"strip": 0, "bin": "git-lfs"}),
    ("dev", "hub", "2.14.2", "hub github", "MIT",
     "https://hub.github.com", "tarball",
     "https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz",
     {"strip": 1, "bin": "bin/hub"}),
    ("dev", "tea", "0.9.2", "Gitea CLI", "MIT",
     "https://gitea.com", "single",
     "https://gitea.com/gitea/tea/releases/download/v0.9.2/tea-0.9.2-linux-amd64",
     {}),
    ("dev", "delta", "0.18.2", "delta diff pager", "MIT",
     "https://github.com/dandavison/delta", "tarball",
     "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "delta"}),
    ("dev", "difftastic", "0.64.0", "difftastic", "MIT",
     "https://github.com/Wilfred/difftastic", "tarball",
     "https://github.com/Wilfred/difftastic/releases/download/0.64.0/difft-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "difft"}),
    ("dev", "dive", "0.13.1", "dive image explorer", "MIT",
     "https://github.com/wagoodman/dive", "tarball",
     "https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_linux_amd64.tar.gz",
     {"strip": 0, "bin": "dive"}),
    ("dev", "k3d", "5.8.3", "k3d", "MIT",
     "https://k3d.io", "single",
     "https://github.com/k3d-io/k3d/releases/download/v5.8.3/k3d-linux-amd64",
     {}),
    ("dev", "k3s", "1.34.2", "k3s", "Apache-2.0",
     "https://k3s.io", "single",
     "https://github.com/k3s-io/k3s/releases/download/v1.34.2%2Bk3s1/k3s",
     {}),
    ("dev", "kind", "0.30.0", "kind", "Apache-2.0",
     "https://kind.sigs.k8s.io", "single",
     "https://github.com/kubernetes-sigs/kind/releases/download/v0.30.0/kind-linux-amd64",
     {}),
    ("dev", "minikube", "1.37.0", "minikube", "Apache-2.0",
     "https://minikube.sigs.k8s.io", "single",
     "https://github.com/kubernetes/minikube/releases/download/v1.37.0/minikube-linux-amd64",
     {}),
    ("dev", "helm", "4.0.0", "Helm", "Apache-2.0",
     "https://helm.sh", "tarball",
     "https://get.helm.sh/helm-v4.0.0-linux-amd64.tar.gz",
     {"strip": 1, "bin": "linux-amd64/helm"}),
    ("dev", "kustomize", "5.7.1", "kustomize", "Apache-2.0",
     "https://kustomize.io", "tarball",
     "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.7.1/kustomize_v5.7.1_linux_amd64.tar.gz",
     {"strip": 0, "bin": "kustomize"}),
    ("dev", "tilt", "0.34.3", "Tilt", "Apache-2.0",
     "https://tilt.dev", "single",
     "https://github.com/tilt-dev/tilt/releases/download/v0.34.3/tilt.0.34.3.linux.x86_64.gz",
     {}),
    ("dev", "skaffold", "2.17.1", "Skaffold", "Apache-2.0",
     "https://skaffold.dev", "single",
     "https://github.com/GoogleContainerTools/skaffold/releases/download/v2.17.1/skaffold-linux-amd64",
     {}),
    ("dev", "argocd", "3.1.7", "Argo CD CLI", "Apache-2.0",
     "https://argo-cd.readthedocs.io", "single",
     "https://github.com/argoproj/argo-cd/releases/download/v3.1.7/argocd-linux-amd64",
     {}),
    ("dev", "flux", "2.7.3", "Flux CLI", "Apache-2.0",
     "https://fluxcd.io", "tarball",
     "https://github.com/fluxcd/flux2/releases/download/v2.7.3/flux_2.7.3_linux_amd64.tar.gz",
     {"strip": 0, "bin": "flux"}),
    ("dev", "terraform", "1.13.3", "Terraform", "BSL-1.1",
     "https://terraform.io", "single",
     "https://releases.hashicorp.com/terraform/1.13.3/terraform_1.13.3_linux_amd64.zip",
     {"inner": "terraform"}),
    ("dev", "opentofu", "1.11.3", "OpenTofu", "MPL-2.0",
     "https://opentofu.org", "tarball",
     "https://github.com/opentofu/opentofu/releases/download/v1.11.3/tofu_1.11.3_linux_amd64.tar.gz",
     {"strip": 0, "bin": "tofu"}),
    ("dev", "packer", "1.14.2", "Packer", "BSL-1.1",
     "https://packer.io", "single",
     "https://releases.hashicorp.com/packer/1.14.2/packer_1.14.2_linux_amd64.zip",
     {"inner": "packer"}),
    ("dev", "vault", "1.20.0", "Vault", "BSL-1.1",
     "https://vaultproject.io", "single",
     "https://releases.hashicorp.com/vault/1.20.0/vault_1.20.0_linux_amd64.zip",
     {"inner": "vault"}),
    ("dev", "dagger", "0.19.3", "Dagger", "Apache-2.0",
     "https://dagger.io", "tarball",
     "https://github.com/dagger/dagger/releases/download/v0.19.3/dagger_v0.19.3_linux_amd64.tar.gz",
     {"strip": 0, "bin": "dagger"}),
    ("dev", "crictl", "1.34.1", "crictl", "Apache-2.0",
     "https://github.com/kubernetes-sigs/cri-tools", "tarball",
     "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.34.1/crictl-v1.34.1-linux-amd64.tar.gz",
     {"strip": 0, "bin": "crictl"}),
    ("dev", "nerdctl", "2.1.7", "nerdctl", "Apache-2.0",
     "https://github.com/containerd/nerdctl", "tarball",
     "https://github.com/containerd/nerdctl/releases/download/v2.1.7/nerdctl-2.1.7-linux-amd64.tar.gz",
     {"strip": 0, "bin": "nerdctl"}),
    ("dev", "ninja", "1.13.2", "Ninja build", "Apache-2.0",
     "https://ninja-build.org", "single",
     "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip",
     {"inner": "ninja"}),
    ("dev", "cmake", "4.2.1", "CMake", "BSD-3",
     "https://cmake.org", "tarball",
     "https://github.com/Kitware/CMake/releases/download/v4.2.1/cmake-4.2.1-linux-x86_64.tar.gz",
     {"strip": 1, "bin": "bin/cmake", "extras": ["ctest:bin/ctest", "cpack:bin/cpack"]}),
    ("dev", "bazelisk", "1.27.0", "Bazelisk", "Apache-2.0",
     "https://github.com/bazelbuild/bazelisk", "single",
     "https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-linux-amd64",
     {}),
    ("dev", "mold", "2.40.4", "mold linker", "MIT",
     "https://github.com/rui314/mold", "tarball",
     "https://github.com/rui314/mold/releases/download/v2.40.4/mold-2.40.4-x86_64-linux.tar.gz",
     {"strip": 1, "bin": "bin/mold"}),
    ("dev", "neofetch", "7.1.0", "neofetch", "MIT",
     "https://github.com/dylanaraps/neofetch", "tarball",
     "https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz",
     {"strip": 1, "bin": "neofetch"}),
    ("dev", "fastfetch", "2.55.0", "fastfetch", "MIT",
     "https://github.com/fastfetch-cli/fastfetch", "tarball",
     "https://github.com/fastfetch-cli/fastfetch/releases/download/2.55.0/fastfetch-linux-amd64.tar.gz",
     {"strip": 0, "bin": "usr/bin/fastfetch"}),
    ("dev", "onefetch", "2.24.1", "onefetch", "MIT",
     "https://github.com/o2sh/onefetch", "tarball",
     "https://github.com/o2sh/onefetch/releases/download/2.24.1/onefetch-linux-x86_64.tar.gz",
     {"strip": 0, "bin": "onefetch"}),
    ("dev", "eww", "0.6.0", "Eww widgets", "MIT",
     "https://github.com/elkowar/eww", "tarball",
     "https://github.com/elkowar/eww/releases/download/v0.6.0/eww-v0.6.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "eww"}),
    ("dev", "zellij", "0.43.1", "Zellij", "MIT",
     "https://github.com/zellij-org/zellij", "tarball",
     "https://github.com/zellij-org/zellij/releases/download/v0.43.1/zellij-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "zellij"}),
    ("dev", "pass", "1.7.4", "pass password store", "GPL-2.0",
     "https://passwordstore.org", "tarball",
     "https://git.zx2c4.com/password-store/snapshot/password-store-1.7.4.tar.xz",
     {"strip": 1, "bin": "src/password-store.sh", "as": "pass"}),
    ("dev", "gopass", "1.15.18", "gopass", "MIT",
     "https://www.gopass.pw", "tarball",
     "https://github.com/gopass/gopass/releases/download/v1.15.18/gopass-1.15.18-linux-amd64.tar.gz",
     {"strip": 0, "bin": "gopass"}),
    ("dev", "age", "1.3.1", "age encryption", "BSD-3",
     "https://github.com/FiloSottile/age", "tarball",
     "https://github.com/FiloSottile/age/releases/download/v1.3.1/age-v1.3.1-linux-amd64.tar.gz",
     {"strip": 0, "bin": "age", "extras": ["age-keygen:age-keygen"]}),
    ("dev", "sops", "3.11.0", "sops secrets", "MPL-2.0",
     "https://github.com/getsops/sops", "single",
     "https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.amd64",
     {}),
    ("dev", "cosign", "2.6.1", "cosign", "Apache-2.0",
     "https://github.com/sigstore/cosign", "single",
     "https://github.com/sigstore/cosign/releases/download/v2.6.1/cosign-linux-amd64",
     {}),
    ("dev", "trivy", "0.68.2", "Trivy scanner", "Apache-2.0",
     "https://github.com/aquasecurity/trivy", "tarball",
     "https://github.com/aquasecurity/trivy/releases/download/v0.68.2/trivy_0.68.2_Linux-64bit.tar.gz",
     {"strip": 0, "bin": "trivy"}),
    ("dev", "grype", "0.101.0", "Grype scanner", "Apache-2.0",
     "https://github.com/anchore/grype", "tarball",
     "https://github.com/anchore/grype/releases/download/v0.101.0/grype_0.101.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "grype"}),
    ("dev", "syft", "1.36.0", "Syft SBOM", "Apache-2.0",
     "https://github.com/anchore/syft", "tarball",
     "https://github.com/anchore/syft/releases/download/v1.36.0/syft_1.36.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "syft"}),
    ("dev", "osv-scanner", "2.2.2", "OSV scanner", "Apache-2.0",
     "https://github.com/google/osv-scanner", "single",
     "https://github.com/google/osv-scanner/releases/download/v2.2.2/osv-scanner_linux_amd64",
     {}),
    ("dev", "nuclei", "3.4.8", "nuclei scanner", "MIT",
     "https://github.com/projectdiscovery/nuclei", "tarball",
     "https://github.com/projectdiscovery/nuclei/releases/download/v3.4.8/nuclei_3.4.8_linux_amd64.tar.gz",
     {"strip": 0, "bin": "nuclei"}),
    ("dev", "subfinder", "2.8.0", "subfinder", "MIT",
     "https://github.com/projectdiscovery/subfinder", "tarball",
     "https://github.com/projectdiscovery/subfinder/releases/download/v2.8.0/subfinder_2.8.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "subfinder"}),
    ("dev", "httpx", "1.7.1", "httpx probe", "MIT",
     "https://github.com/projectdiscovery/httpx", "tarball",
     "https://github.com/projectdiscovery/httpx/releases/download/v1.7.1/httpx_1.7.1_linux_amd64.tar.gz",
     {"strip": 0, "bin": "httpx"}),
    ("dev", "amass", "4.2.0", "OWASP Amass", "Apache-2.0",
     "https://github.com/owasp-amass/amass", "single",
     "https://github.com/owasp-amass/amass/releases/download/v4.2.0/amass_linux_amd64",
     {}),
    ("dev", "ffuf", "2.1.0", "ffuf fuzzer", "MIT",
     "https://github.com/ffuf/ffuf", "tarball",
     "https://github.com/ffuf/ffuf/releases/download/v2.1.0/ffuf_2.1.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "ffuf"}),
    ("dev", "gobuster", "3.6.0", "Gobuster", "Apache-2.0",
     "https://github.com/OJ/gobuster", "tarball",
     "https://github.com/OJ/gobuster/releases/download/v3.6.0/gobuster_Linux_x86_64.tar.gz",
     {"strip": 0, "bin": "gobuster"}),
    ("dev", "termshark", "2.5.0", "Termshark", "MIT",
     "https://github.com/gcla/termshark", "tarball",
     "https://github.com/gcla/termshark/releases/download/v2.5.0/termshark_2.5.0_linux_x64.tar.gz",
     {"strip": 0, "bin": "termshark"}),
    ("dev", "mitmproxy", "12.1.2", "mitmproxy", "MIT",
     "https://mitmproxy.org", "tarball",
     "https://github.com/mitmproxy/mitmproxy/releases/download/v12.1.2/mitmproxy-12.1.2-linux.tar.gz",
     {"strip": 0, "bin": "mitmproxy", "extras": ["mitmweb:mitmweb", "mitmdump:mitmdump"]}),
    ("dev", "goreplay", "1.3.4", "GoReplay", "MIT",
     "https://github.com/buger/goreplay", "tarball",
     "https://github.com/buger/goreplay/releases/download/v1.3.4/gor_1.3.4_x64.tar.gz",
     {"strip": 0, "bin": "gor", "as": "goreplay"}),
    ("dev", "evans", "0.10.11", "Evans gRPC", "MIT",
     "https://github.com/ktr0731/evans", "tarball",
     "https://github.com/ktr0731/evans/releases/download/v0.10.11/evans_linux_amd64.tar.gz",
     {"strip": 0, "bin": "evans"}),
    ("dev", "grpcurl", "1.9.3", "grpcurl", "MIT",
     "https://github.com/fullstorydev/grpcurl", "tarball",
     "https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz",
     {"strip": 0, "bin": "grpcurl"}),
    ("dev", "buf", "1.57.2", "Buf protobuf", "Apache-2.0",
     "https://github.com/bufbuild/buf", "single",
     "https://github.com/bufbuild/buf/releases/download/v1.57.2/buf-Linux-x86_64",
     {}),
    ("dev", "protoc", "32.1", "protoc", "BSD-3",
     "https://github.com/protocolbuffers/protobuf", "single",
     "https://github.com/protocolbuffers/protobuf/releases/download/v32.1/protoc-32.1-linux-x86_64.zip",
     {"inner": "bin/protoc"}),
    ("dev", "overmind", "2.5.1", "Overmind procman", "MIT",
     "https://github.com/DarthSim/overmind", "single",
     "https://github.com/DarthSim/overmind/releases/download/v2.5.1/overmind-v2.5.1-linux-amd64.gz",
     {}),
    ("dev", "hivemind", "1.1.0", "Hivemind procman", "MIT",
     "https://github.com/DarthSim/hivemind", "single",
     "https://github.com/DarthSim/hivemind/releases/download/v1.1.0/hivemind-v1.1.0-linux-amd64.gz",
     {}),
    ("dev", "goreman", "0.3.19", "goreman procman", "MIT",
     "https://github.com/mattn/goreman", "single",
     "https://github.com/mattn/goreman/releases/download/v0.3.19/goreman_linux_amd64.zip",
     {"inner": "goreman"}),
    ("dev", "caddy", "2.10.2", "Caddy server", "Apache-2.0",
     "https://github.com/caddyserver/caddy", "tarball",
     "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_linux_amd64.tar.gz",
     {"strip": 0, "bin": "caddy"}),
    ("dev", "traefik", "3.6.1", "Traefik proxy", "MIT",
     "https://github.com/traefik/traefik", "tarball",
     "https://github.com/traefik/traefik/releases/download/v3.6.1/traefik_v3.6.1_linux_amd64.tar.gz",
     {"strip": 0, "bin": "traefik"}),
]

LANGS = [
    ("langs", "go", "1.25.4", "Go toolchain", "BSD-3",
     "https://go.dev", "tarball",
     "https://go.dev/dl/go1.25.4.linux-amd64.tar.gz",
     {"strip": 1, "bin": "bin/go", "extras": ["gofmt:bin/gofmt"]}),
    ("langs", "nodejs", "22.14.0", "Node.js LTS", "MIT",
     "https://nodejs.org", "tarball",
     "https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz",
     {"strip": 1, "bin": "bin/node", "extras": ["npm:bin/npm", "npx:bin/npx"]}),
    ("langs", "deno", "2.5.4", "Deno", "MIT",
     "https://deno.com", "single",
     "https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip",
     {"inner": "deno"}),
    ("langs", "bun", "1.3.5", "Bun", "MIT",
     "https://bun.sh", "single",
     "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip",
     {"inner": "bun-linux-x64/bun"}),
    ("langs", "rustup", "1.28.2", "rustup", "MIT",
     "https://rustup.rs", "single",
     "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init",
     {"as": "rustup-init"}),
    ("langs", "uv", "0.9.8", "uv python manager", "MIT",
     "https://docs.astral.sh/uv", "tarball",
     "https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "uv", "extras": ["uvx:uvx"]}),
    ("langs", "ruff", "0.14.3", "Ruff linter", "MIT",
     "https://docs.astral.sh/ruff", "tarball",
     "https://github.com/astral-sh/ruff/releases/latest/download/ruff-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "ruff"}),
    ("langs", "zig", "0.15.1", "Zig", "MIT",
     "https://ziglang.org", "tarball",
     "https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz",
     {"strip": 1, "bin": "zig"}),
    ("langs", "julia", "1.12.1", "Julia", "MIT",
     "https://julialang.org", "tarball",
     "https://julialang-s3.julialang.org/bin/linux/x64/1.12/julia-1.12.1-linux-x86_64.tar.gz",
     {"strip": 1, "bin": "bin/julia"}),
    ("langs", "nim", "2.2.4", "Nim", "MIT",
     "https://nim-lang.org", "tarball",
     "https://nim-lang.org/download/nim-2.2.4-linux_x64.tar.xz",
     {"strip": 1, "bin": "bin/nim"}),
    ("langs", "dart", "3.9.2", "Dart SDK", "BSD-3",
     "https://dart.dev", "single",
     "https://storage.googleapis.com/dart-archive/channels/stable/release/3.9.2/sdk/dartsdk-linux-x64-release.zip",
     {"inner": "dart-sdk/bin/dart"}),
    ("langs", "kotlin", "2.2.20", "Kotlin compiler", "Apache-2.0",
     "https://kotlinlang.org", "single",
     "https://github.com/JetBrains/kotlin/releases/download/v2.2.20/kotlin-compiler-2.2.20.zip",
     {"inner": "kotlinc/bin/kotlinc",
      "extras": ["kotlin:kotlinc/bin/kotlin"]}),
    ("langs", "elixir", "1.19.4", "Elixir", "Apache-2.0",
     "https://elixir-lang.org", "single",
     "https://github.com/elixir-lang/elixir/releases/download/v1.19.4/elixir-otp-27.zip",
     {"inner": "bin/elixir", "extras": ["mix:bin/mix", "iex:bin/iex"]}),
    ("langs", "ghc", "9.12.2", "GHC Haskell", "BSD-3",
     "https://haskell.org/ghc", "tarball",
     "https://downloads.haskell.org/ghc/9.12.2/ghc-9.12.2-x86_64-deb12-linux.tar.xz",
     {"strip": 1, "bin": "bin/ghc", "extras": ["ghci:bin/ghci", "runghc:bin/runghc"]}),
    ("langs", "dotnet", "9.0.306", ".NET SDK", "MIT",
     "https://dotnet.microsoft.com", "tarball",
     "https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.306/dotnet-sdk-9.0.306-linux-x64.tar.gz",
     {"strip": 0, "bin": "dotnet"}),
    ("langs", "maven", "3.9.11", "Maven", "Apache-2.0",
     "https://maven.apache.org", "tarball",
     "https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz",
     {"strip": 1, "bin": "bin/mvn"}),
    ("langs", "gradle", "8.14.3", "Gradle", "Apache-2.0",
     "https://gradle.org", "single",
     "https://services.gradle.org/distributions/gradle-8.14.3-bin.zip",
     {"inner": "gradle-8.14.3/bin/gradle", "as": "gradle"}),
    ("langs", "ant", "1.10.15", "Ant", "Apache-2.0",
     "https://ant.apache.org", "tarball",
     "https://dlcdn.apache.org/ant/binaries/apache-ant-1.10.15-bin.tar.gz",
     {"strip": 1, "bin": "bin/ant"}),
]

NET = [
    ("net", "xh", "0.24.1", "xh HTTP client", "MIT",
     "https://github.com/ducaale/xh", "tarball",
     "https://github.com/ducaale/xh/releases/download/v0.24.1/xh-v0.24.1-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "xh"}),
    ("net", "k6", "1.3.0", "k6 load testing", "AGPL-3.0",
     "https://k6.io", "tarball",
     "https://github.com/grafana/k6/releases/download/v1.3.0/k6-v1.3.0-linux-amd64.tar.gz",
     {"strip": 0, "bin": "k6"}),
    ("net", "vegeta", "12.12.0", "vegeta load testing", "MIT",
     "https://github.com/tsenart/vegeta", "tarball",
     "https://github.com/tsenart/vegeta/releases/download/v12.12.0/vegeta_12.12.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "vegeta"}),
    ("net", "hey", "0.1.4", "hey load generator", "Apache-2.0",
     "https://github.com/rakyll/hey", "single",
     "https://github.com/rakyll/hey/releases/download/v0.1.4/hey_linux_amd64",
     {}),
    ("net", "step-cli", "0.28.4", "step CLI", "Apache-2.0",
     "https://smallstep.com/cli", "tarball",
     "https://github.com/smallstep/cli/releases/download/v0.28.4/step_linux_0.28.4_amd64.tar.gz",
     {"strip": 0, "bin": "step", "as": "step-cli"}),
    ("net", "mkcert", "1.4.9", "mkcert certs", "MPL-2.0",
     "https://github.com/FiloSottile/mkcert", "single",
     "https://github.com/FiloSottile/mkcert/releases/download/v1.4.9/mkcert-v1.4.9-linux-amd64",
     {}),
    ("net", "cloudflared", "2025.10.0", "cloudflared tunnel", "Apache-2.0",
     "https://developers.cloudflare.com/cloudflare-one/", "single",
     "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64",
     {}),
    ("net", "frp", "0.65.0", "frp proxy", "Apache-2.0",
     "https://github.com/fatedier/frp", "tarball",
     "https://github.com/fatedier/frp/releases/download/v0.65.0/frp_0.65.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "frpc", "extras": ["frps:frps"]}),
    ("net", "bore", "0.5.3", "bore tunnels", "MIT",
     "https://github.com/ekzhang/bore", "tarball",
     "https://github.com/ekzhang/bore/releases/download/v0.5.3/bore-v0.5.3-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "bore"}),
    ("net", "rathole", "0.5.3", "rathole tunnel", "Apache-2.0",
     "https://github.com/rapiz1/rathole", "single",
     "https://github.com/rapiz1/rathole/releases/download/v0.5.3/rathole-x86_64-unknown-linux-gnu.zip",
     {"inner": "rathole"}),
    ("net", "chisel", "1.11.3", "chisel tunnels", "MIT",
     "https://github.com/jpillora/chisel", "single",
     "https://github.com/jpillora/chisel/releases/download/v1.11.3/chisel_1.11.3_linux_amd64.gz",
     {}),
    ("net", "gost", "3.2.2", "GOST proxy", "MIT",
     "https://github.com/ginuerzh/gost", "single",
     "https://github.com/ginuerzh/gost/releases/download/v3.2.2/gost-linux-amd64-3.2.2.gz",
     {}),
    ("net", "v2ray", "5.38.0", "V2Ray", "MIT",
     "https://v2fly.org", "single",
     "https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip",
     {"inner": "v2ray"}),
    ("net", "xray", "26.2.0", "Xray-core", "MPL-2.0",
     "https://github.com/XTLS/Xray-core", "single",
     "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip",
     {"inner": "xray"}),
    ("net", "sing-box", "1.12.4", "sing-box proxy", "GPL-3.0",
     "https://sing-box.sagernet.org", "tarball",
     "https://github.com/SagerNet/sing-box/releases/download/v1.12.4/sing-box-1.12.4-linux-amd64.tar.gz",
     {"strip": 0, "bin": "sing-box"}),
    ("net", "mihomo", "1.19.13", "Mihomo proxy", "GPL-3.0",
     "https://github.com/MetaCubeX/mihomo", "single",
     "https://github.com/MetaCubeX/mihomo/releases/download/v1.19.13/mihomo-linux-amd64-v1.19.13.gz",
     {}),
    ("net", "hysteria", "2.6.4", "Hysteria proxy", "MIT",
     "https://github.com/apernet/hysteria", "single",
     "https://github.com/apernet/hysteria/releases/download/app/v2.6.4/hysteria-linux-amd64",
     {}),
    ("net", "wstunnel", "10.4.2", "wstunnel", "MIT",
     "https://github.com/erebe/wstunnel", "tarball",
     "https://github.com/erebe/wstunnel/releases/download/v10.4.2/wstunnel_10.4.2_linux_x86_64.tar.gz",
     {"strip": 0, "bin": "wstunnel"}),
    ("net", "tailscale", "1.90.7", "Tailscale", "BSD-3",
     "https://tailscale.com", "tarball",
     "https://pkgs.tailscale.com/stable/tailscale_1.90.7_amd64.tgz",
     {"strip": 1, "bin": "tailscale", "extras": ["tailscaled:tailscaled"]}),
    ("net", "wireproxy", "1.0.9", "wireproxy", "MIT",
     "https://github.com/pufferffish/wireproxy", "tarball",
     "https://github.com/pufferffish/wireproxy/releases/download/v1.0.9/wireproxy_linux_amd64.tar.gz",
     {"strip": 0, "bin": "wireproxy"}),
    ("net", "curlie", "1.8.2", "curlie HTTP", "MIT",
     "https://github.com/rs/curlie", "tarball",
     "https://github.com/rs/curlie/releases/download/v1.8.2/curlie_1.8.2_linux_amd64.tar.gz",
     {"strip": 0, "bin": "curlie"}),
    ("net", "hurl", "7.0.0", "Hurl HTTP tests", "Apache-2.0",
     "https://github.com/Orange-OpenSource/hurl", "tarball",
     "https://github.com/Orange-OpenSource/hurl/releases/download/7.0.0/hurl-7.0.0-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "hurl"}),
    ("net", "posting", "3.3.0", "Posting API client", "MIT",
     "https://github.com/darrenburns/posting", "tarball",
     "https://github.com/darrenburns/posting/releases/download/3.3.0/posting_3.3.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "posting"}),
    ("net", "websocat", "1.15.0", "websocat", "MIT",
     "https://github.com/vi/websocat", "single",
     "https://github.com/vi/websocat/releases/download/v1.15.0/websocat.x86_64-unknown-linux-musl",
     {}),
]

UTILS = [
    ("utils", "lf", "r34", "lf file manager", "MIT",
     "https://github.com/gokcehan/lf", "tarball",
     "https://github.com/gokcehan/lf/releases/download/r34/lf-linux-amd64.tar.gz",
     {"strip": 0, "bin": "lf"}),
    ("utils", "xplr", "1.1.0", "xplr file manager", "MIT",
     "https://github.com/sayanarijit/xplr", "tarball",
     "https://github.com/sayanarijit/xplr/releases/download/v1.1.0/xplr-v1.1.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "xplr"}),
    ("utils", "superfile", "1.3.1", "superfile manager", "MIT",
     "https://github.com/yorukot/superfile", "tarball",
     "https://github.com/yorukot/superfile/releases/download/v1.3.1/superfile-linux-amd64.tar.gz",
     {"strip": 0, "bin": "spf", "as": "superfile"}),
    ("utils", "nushell", "0.109.1", "Nushell", "MIT",
     "https://nushell.sh", "tarball",
     "https://github.com/nushell/nushell/releases/download/0.109.1/nu-0.109.1-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "nu", "as": "nushell"}),
    ("utils", "elvish", "0.21.0", "Elvish shell", "BSD-2",
     "https://elv.sh", "tarball",
     "https://github.com/elves/elvish/releases/download/v0.21.0/elvish-v0.21.0-linux-amd64.tar.gz",
     {"strip": 0, "bin": "elvish"}),
    ("utils", "powershell", "7.6.0", "PowerShell", "MIT",
     "https://github.com/PowerShell/PowerShell", "tarball",
     "https://github.com/PowerShell/PowerShell/releases/download/v7.6.0/powershell-7.6.0-linux-x64.tar.gz",
     {"strip": 0, "bin": "pwsh", "as": "powershell"}),
    ("utils", "oh-my-posh", "29.4.0", "Oh My Posh prompt", "MIT",
     "https://ohmyposh.dev", "single",
     "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v29.4.0/posh-linux-amd64",
     {"as": "oh-my-posh"}),
    ("utils", "atuin", "18.8.0", "Atuin history", "MIT",
     "https://atuin.sh", "tarball",
     "https://github.com/atuinsh/atuin/releases/download/v18.8.0/atuin-v18.8.0-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "atuin"}),
    ("utils", "jq", "1.8.1", "jq JSON", "MIT",
     "https://jqlang.github.io/jq", "single",
     "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64",
     {}),
    ("utils", "yq", "4.48.2", "yq YAML", "MIT",
     "https://github.com/mikefarah/yq", "single",
     "https://github.com/mikefarah/yq/releases/download/v4.48.2/yq_linux_amd64",
     {}),
    ("utils", "fzf", "0.65.2", "fzf finder", "MIT",
     "https://github.com/junegunn/fzf", "tarball",
     "https://github.com/junegunn/fzf/releases/download/v0.65.2/fzf-0.65.2-linux_amd64.tar.gz",
     {"strip": 0, "bin": "fzf"}),
    ("utils", "ripgrep", "14.1.1", "ripgrep", "MIT",
     "https://github.com/BurntSushi/ripgrep", "tarball",
     "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "rg", "as": "ripgrep"}),
    ("utils", "fd", "10.3.0", "fd find", "MIT",
     "https://github.com/sharkdp/fd", "tarball",
     "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "fd"}),
    ("utils", "bat", "0.26.1", "bat cat", "MIT",
     "https://github.com/sharkdp/bat", "tarball",
     "https://github.com/sharkdp/bat/releases/download/v0.26.1/bat-v0.26.1-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "bat"}),
    ("utils", "eza", "0.23.4", "eza ls", "MIT",
     "https://github.com/eza-community/eza", "tarball",
     "https://github.com/eza-community/eza/releases/download/v0.23.4/eza_x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "eza"}),
    ("utils", "zoxide", "0.9.7", "zoxide cd", "MIT",
     "https://github.com/ajeetdsouza/zoxide", "tarball",
     "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.7/zoxide-0.9.7-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "zoxide"}),
    ("utils", "tokei", "13.0.0", "tokei code stats", "MIT",
     "https://github.com/XAMPPRocky/tokei", "tarball",
     "https://github.com/XAMPPRocky/tokei/releases/download/v13.0.0/tokei-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "tokei"}),
    ("utils", "hyperfine", "1.19.0", "hyperfine bench", "MIT",
     "https://github.com/sharkdp/hyperfine", "tarball",
     "https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine-v1.19.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "hyperfine"}),
    ("utils", "just", "1.43.0", "just runner", "CC0-1.0",
     "https://github.com/casey/just", "tarball",
     "https://github.com/casey/just/releases/download/1.43.0/just-1.43.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "just"}),
    ("utils", "dust", "1.2.3", "dust du", "Apache-2.0",
     "https://github.com/bootandy/dust", "tarball",
     "https://github.com/bootandy/dust/releases/download/v1.2.3/dust-v1.2.3-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "dust"}),
    ("utils", "procs", "0.14.10", "procs ps", "MIT",
     "https://github.com/dalancey/procs", "single",
     "https://github.com/dalancey/procs/releases/download/v0.14.10/procs-0.14.10-x86_64-linux.zip",
     {"inner": "procs"}),
    ("utils", "bottom", "0.11.2", "bottom monitor", "MIT",
     "https://github.com/ClementTsang/bottom", "tarball",
     "https://github.com/ClementTsang/bottom/releases/download/0.11.2/bottom_x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "btm", "as": "bottom"}),
    ("utils", "btop", "1.4.4", "btop monitor", "Apache-2.0",
     "https://github.com/aristocratos/btop", "tarball",
     "https://github.com/aristocratos/btop/releases/download/v1.4.4/btop-x86_64-linux-musl.tbz",
     {"strip": 0, "bin": "bin/btop"}),
    ("utils", "zenith", "0.14.1", "zenith monitor", "MIT",
     "https://github.com/bvaisvil/zenith", "tarball",
     "https://github.com/bvaisvil/zenith/releases/download/0.14.1/zenith-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "zenith"}),
    ("utils", "bandwhich", "0.23.2", "bandwhich net", "MIT",
     "https://github.com/imsnif/bandwhich", "tarball",
     "https://github.com/imsnif/bandwhich/releases/download/bandwhich-v0.23.2/bandwhich-v0.23.2-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "bandwhich"}),
    ("utils", "gping", "1.19.0", "gping", "MIT",
     "https://github.com/orf/gping", "tarball",
     "https://github.com/orf/gping/releases/download/gping-v1.19.0/gping-v1.19.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "gping"}),
    ("utils", "trippy", "0.14.0", "trippy traceroute", "Apache-2.0",
     "https://github.com/fujiapple852/trippy", "tarball",
     "https://github.com/fujiapple852/trippy/releases/download/0.14.0/trippy-0.14.0-x86_64-unknown-linux-gnu.tar.gz",
     {"strip": 0, "bin": "trip", "as": "trippy"}),
    ("utils", "dog", "0.1.0", "dog DNS", "EPL-2.0",
     "https://github.com/ogham/dog", "single",
     "https://github.com/ogham/dog/releases/download/v0.1.0/dog-v0.1.0-x86_64-unknown-linux-gnu.zip",
     {"inner": "bin/dog"}),
    ("utils", "cpufetch", "1.1.0", "cpufetch", "MIT",
     "https://github.com/Dr-Noob/cpufetch", "tarball",
     "https://github.com/Dr-Noob/cpufetch/releases/download/1.1.0/cpufetch_1.1.0_linux_x86_64.tar.gz",
     {"strip": 0, "bin": "cpufetch"}),
    ("utils", "fx", "38.0.0", "fx JSON viewer", "MIT",
     "https://github.com/antonmedv/fx", "tarball",
     "https://github.com/antonmedv/fx/releases/download/38.0.0/fx_linux_amd64.tar.gz",
     {"strip": 0, "bin": "fx"}),
    ("utils", "jless", "0.9.0", "jless JSON viewer", "MIT",
     "https://github.com/PaulJuliusMartinez/jless", "single",
     "https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip",
     {"inner": "jless"}),
    ("utils", "viddy", "0.4.0", "viddy watch", "MIT",
     "https://github.com/sachaos/viddy", "tarball",
     "https://github.com/sachaos/viddy/releases/download/v0.4.0/viddy_0.4.0_Linux_x86_64.tar.gz",
     {"strip": 0, "bin": "viddy"}),
    ("utils", "watchexec", "2.3.2", "watchexec", "Apache-2.0",
     "https://github.com/watchexec/watchexec", "tarball",
     "https://github.com/watchexec/watchexec/releases/download/v2.3.2/watchexec-2.3.2-x86_64-unknown-linux-musl.tar.xz",
     {"strip": 0, "bin": "watchexec"}),
    ("utils", "dasel", "3.0.3", "dasel data tool", "MIT",
     "https://github.com/TomWright/dasel", "tarball",
     "https://github.com/TomWright/dasel/releases/download/v3.0.3/dasel_linux_amd64.tar.gz",
     {"strip": 0, "bin": "dasel"}),
    ("utils", "gojq", "0.12.17", "gojq", "MIT",
     "https://github.com/itchyny/gojq", "tarball",
     "https://github.com/itchyny/gojq/releases/download/v0.12.17/gojq_v0.12.17_linux_amd64.tar.gz",
     {"strip": 0, "bin": "gojq"}),
    ("utils", "fq", "0.13.0", "fq data tool", "MIT",
     "https://github.com/wader/fq", "tarball",
     "https://github.com/wader/fq/releases/download/v0.13.0/fq_0.13.0_linux_amd64.tar.gz",
     {"strip": 0, "bin": "fq"}),
    ("utils", "miller", "6.15.0", "miller CSV", "BSD-2",
     "https://github.com/johnkerl/miller", "tarball",
     "https://github.com/johnkerl/miller/releases/download/v6.15.0/miller-6.15.0-linux-amd64.tar.gz",
     {"strip": 0, "bin": "mlr", "as": "miller"}),
    ("utils", "xsv", "0.13.0", "xsv CSV", "MIT",
     "https://github.com/BurntSushi/xsv", "tarball",
     "https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "xsv"}),
    ("utils", "qsv", "3.3.0", "qsv CSV", "MIT",
     "https://github.com/dathere/qsv", "single",
     "https://github.com/dathere/qsv/releases/download/3.3.0/qsv-3.3.0-x86_64-unknown-linux-musl.zip",
     {"inner": "qsv"}),
    ("utils", "usql", "0.17.1", "usql SQL", "MIT",
     "https://github.com/xo/usql", "tarball",
     "https://github.com/xo/usql/releases/download/v0.17.1/usql-0.17.1-linux-amd64.tar.gz",
     {"strip": 0, "bin": "usql"}),
    ("utils", "starship", "1.26.0", "Starship prompt", "ISC",
     "https://github.com/starship/starship", "tarball",
     "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz",
     {"strip": 0, "bin": "starship"}),
    ("utils", "yazi", "25.5.31", "Yazi file manager", "MIT",
     "https://github.com/sxyazi/yazi", "single",
     "https://github.com/sxyazi/yazi/releases/download/v25.5.31/yazi-x86_64-unknown-linux-musl.zip",
     {"inner": "yazi-x86_64-unknown-linux-musl/yazi",
      "extras": ["ya:yazi-x86_64-unknown-linux-musl/ya"]}),
]

GAMES = [
    ("games", "heroic", "2.18.1", "Heroic launcher", "GPL-3.0",
     "https://heroicgameslauncher.com", "appimage",
     "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.18.1/Heroic-2.18.1-linux-x86_64.AppImage",
     {}),
    ("games", "prismlauncher", "9.5", "PrismLauncher", "GPL-3.0",
     "https://prismlauncher.org", "appimage",
     "https://github.com/PrismLauncher/PrismLauncher/releases/download/9.5/PrismLauncher-Linux-9.5-x86_64.AppImage",
     {}),
    ("games", "protonup-qt", "2.12.0", "ProtonUp-Qt", "GPL-3.0",
     "https://github.com/DavidoTek/ProtonUp-Qt", "appimage",
     "https://github.com/DavidoTek/ProtonUp-Qt/releases/download/v2.12.0/pupgui2-2.12.0-x86_64.AppImage",
     {"as": "protonup-qt"}),
    ("games", "openra", "20250330", "OpenRA", "GPL-3.0",
     "https://openra.net", "appimage",
     "https://github.com/OpenRA/OpenRA/releases/download/release-20250330/OpenRA-release-20250330-x86_64.AppImage",
     {}),
    ("games", "gzdoom", "4.14.2", "GZDoom", "GPL-3.0",
     "https://zdoom.org", "tarball",
     "https://github.com/ZDoom/gzdoom/releases/download/g4.14.2/gzdoom-4-14-2-Linux.tar.gz",
     {"strip": 0, "bin": "gzdoom"}),
    ("games", "dwarf-fortress", "50.15", "Dwarf Fortress", "proprietary",
     "http://bay12games.com", "tarball",
     "http://www.bay12games.com/dwarves/df_50_15_linux.tar.bz2",
     {"strip": 1, "bin": "df", "as": "dwarf-fortress"}),
    ("games", "devilutionx", "1.5.4", "DevilutionX Diablo", "custom",
     "https://github.com/diasurgical/devilutionX", "tarball",
     "https://github.com/diasurgical/devilutionX/releases/download/1.5.4/devilutionx-linux-x86_64.tar.xz",
     {"strip": 0, "bin": "devilutionx"}),
    ("games", "openttd", "15.0", "OpenTTD", "GPL-2.0",
     "https://openttd.org", "tarball",
     "https://cdn.openttd.org/openttd-releases/15.0/openttd-15.0-linux-generic-amd64.tar.xz",
     {"strip": 1, "bin": "openttd"}),
    ("games", "teeworlds", "0.7.5", "Teeworlds", "BSD-3",
     "https://teeworlds.com", "tarball",
     "https://www.teeworlds.com/files/teeworlds-0.7.5-linux_x86_64.tar.gz",
     {"strip": 1, "bin": "teeworlds"}),
]

AI = [
    ("ai", "ollama", "0.17.1", "Ollama LLMs", "MIT",
     "https://ollama.com", "tarball",
     "https://github.com/ollama/ollama/releases/download/v0.17.1/ollama-linux-amd64.tgz",
     {"strip": 0, "bin": "bin/ollama"}),
    ("ai", "jan", "0.6.9", "Jan AI chat", "AGPL-3.0",
     "https://jan.ai", "appimage",
     "https://github.com/menloresearch/jan/releases/download/v0.6.9/jan-linux-x86_64-0.6.9.AppImage",
     {}),
]

BACKUP = [
    ("backup", "restic", "0.18.1", "restic backup", "BSD-2",
     "https://restic.net", "single",
     "https://github.com/restic/restic/releases/download/v0.18.1/restic_0.18.1_linux_amd64.bz2",
     {}),
    ("backup", "borgbackup", "1.4.2", "BorgBackup", "BSD-3",
     "https://borgbackup.org", "single",
     "https://github.com/borgbackup/borg/releases/download/1.4.2/borg-linux64",
     {"as": "borgbackup"}),
    ("backup", "kopia", "0.22.0", "Kopia backup", "Apache-2.0",
     "https://kopia.io", "tarball",
     "https://github.com/kopia/kopia/releases/download/v0.22.0/kopia-0.22.0-linux-x64.tar.gz",
     {"strip": 0, "bin": "kopia"}),
    ("backup", "syncthing", "2.0.11", "Syncthing", "MPL-2.0",
     "https://syncthing.net", "tarball",
     "https://github.com/syncthing/syncthing/releases/download/v2.0.11/syncthing-linux-amd64-v2.0.11.tar.gz",
     {"strip": 1, "bin": "syncthing"}),
    ("backup", "nextcloud", "3.18.1", "Nextcloud client", "GPL-2.0",
     "https://nextcloud.com", "appimage",
     "https://github.com/nextcloud-releases/desktop/releases/download/v3.18.1/Nextcloud-3.18.1-x86_64.AppImage",
     {"as": "nextcloud-client"}),
]

SECURITY = [
    ("security", "bitwarden", "2026.1.0", "Bitwarden", "GPL-3.0",
     "https://bitwarden.com", "appimage",
     "https://github.com/bitwarden/clients/releases/download/desktop-v2026.1.0/Bitwarden-2026.1.0-x86_64.AppImage",
     {}),
    ("security", "keepassxc", "2.7.10", "KeePassXC", "GPL-3.0",
     "https://keepassxc.org", "appimage",
     "https://github.com/keepassxreboot/keepassxc/releases/download/2.7.10/KeePassXC-2.7.10-x86_64.AppImage",
     {}),
    ("security", "onionshare", "2.6.3", "OnionShare", "GPL-3.0",
     "https://onionshare.org", "appimage",
     "https://github.com/onionshare/onionshare/releases/download/v2.6.3/OnionShare-2.6.3.AppImage",
     {}),
]

ALL = (RECIPES + DEV + LANGS + NET + UTILS + GAMES + AI + BACKUP + SECURITY)


def emit(row):
    cat, name, ver, desc, lic, home, kind, url, o = row
    urlbase = url.split("?")[0].rstrip("/").split("/")[-1]
    if not urlbase:
        urlbase = name
    # exact download filename: sanitized URL basename, or explicit override
    dlname = o.get("file", urlbase)
    lines = [f'package "{name}" {{', f'  version = "{ver}"',
             f'  description = "{desc}"', f'  license = "{lic}"',
             f'  homepage = "{home}"', '  binary {', f'    url = "{url}"']
    if "file" in o:
        lines.append(f'    file = "{o["file"]}"')
    lines += [f'    format = "{kind}"', '  }',
              '  depends {', '    "glibc"', '  }', '  install {']
    link = o.get("as", name)
    if kind == "appimage":
        lines += [
            f'    command "mkdir -p ${{destdir}}/opt/{name} ${{destdir}}/bin"',
            f'    command "cp ${{srcdir}}/{dlname} ${{destdir}}/opt/{name}/{name}.AppImage"',
            f'    command "chmod +x ${{destdir}}/opt/{name}/{name}.AppImage"',
            f'    command "ln -sf ../opt/{name}/{name}.AppImage ${{destdir}}/bin/{link}"',
        ]
    elif kind == "single":
        staged = o.get("inner", dlname)
        if "inner" not in o:
            if dlname.endswith(".gz"):
                staged = dlname[:-3]
            elif dlname.endswith(".bz2"):
                staged = dlname[:-4]
        lines += [
            f'    command "mkdir -p ${{destdir}}/bin"',
            f'    command "cp ./{staged} ${{destdir}}/bin/{link}"',
            f'    command "chmod +x ${{destdir}}/bin/{link}"',
        ]
        for extra in o.get("extras", []):
            ename, epath = extra.split(":", 1)
            lines += [
                f'    command "cp ./{epath} ${{destdir}}/bin/{ename}"',
                f'    command "chmod +x ${{destdir}}/bin/{ename}"',
            ]
    elif kind == "tarball":
        strip = " --strip-components=1" if o.get("strip") else ""
        lines += [
            f'    command "mkdir -p ${{destdir}}/opt/{name} ${{destdir}}/bin"',
            f'    command "tar -xf ${{srcdir}}/{dlname} -C ${{destdir}}/opt/{name}{strip}"',
            f'    command "chmod +x ${{destdir}}/opt/{name}/{o["bin"]}"',
            f'    command "ln -sf ../opt/{name}/{o["bin"]} ${{destdir}}/bin/{link}"',
        ]
        for extra in o.get("extras", []):
            ename, epath = extra.split(":", 1)
            lines += [
                f'    command "chmod +x ${{destdir}}/opt/{name}/{epath}"',
                f'    command "ln -sf ../opt/{name}/{epath} ${{destdir}}/bin/{ename}"',
            ]
    else:
        raise ValueError(f"bad kind {kind}")
    lines += ['  }', '}']
    return "\n".join(lines) + "\n"


def main():
    out = sys.argv[1]
    seen = set()
    n = 0
    for row in ALL:
        cat, name = row[0], row[1]
        if name in seen:
            print(f"DUPLICATE: {name}", file=sys.stderr)
            sys.exit(1)
        seen.add(name)
        d = os.path.join(out, cat)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, name + ".vnb"), "w") as f:
            f.write(emit(row))
        n += 1
    print(f"wrote {n} recipes to {out}")


if __name__ == "__main__":
    main()
