---
dontChroot: false
timeout: 120
script:
  - rm -f /etc/sddm.conf.d/autologin.conf
  - rm -f /etc/sudoers.d/live
  - sed -i 's/^# *%wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers
  - test "${USER}" != exedra && userdel -r exedra || true
