---
dontChroot: false
timeout: 300
script:
  - bootctl --esp-path=/boot install
  - cp /usr/lib/modules/*/vmlinuz /boot/vmlinuz-exedra
  - UUID=$(blkid -s UUID -o value $(findmnt -no SOURCE /)) && printf 'timeout 5\ndefault exedra\n' > /boot/loader/loader.conf && printf 'title Exedra\nlinux /vmlinuz-exedra\ninitrd /initramfs-exedra.img\noptions root=UUID=%s console=ttyS0,115200 quiet\n' "$UUID" > /boot/loader/entries/exedra.conf
